In [1]:
import numpy as np

# Multiplication

In [2]:
u = np.array([2, 7, 5, 6])
v = np.array([3, 4, 8, 6])

In [6]:
print(u+v)

print(u-v)

print(2*v)

[ 5 11 13 12]
[-1  3 -3  0]
[ 6  8 16 12]


## Vector - Vector multiplication

In [9]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]

    result = 0.0
    for i in range(n):
        result += u[i]*v[i]

    return result

In [10]:
vector_vector_multiplication(u,v)

110.0

In [13]:
u.shape[0]

4